# Generated by Django 5.2.6 on 2026-09-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_localized_spaces_and_occasions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='Уникальные посетители')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статистика сайта за день',
                'verbose_name_plural': 'Статистика сайта по дням',
                'ordering': ('-date',),
            },
        ),
    ]
