# Generated by Django 5.2.6 on 2026-09-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_sitevisitdaily'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='submission_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Ключ отправки'),
        ),
    ]
