# Generated by Django 5.2.6 on 2026-09-26 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_complaint_and_spaces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ('-created_at', '-pk'), 'verbose_name': 'Mehmon shikoyati', 'verbose_name_plural': 'Mehmon shikoyatlari'},
        ),
        migrations.AlterModelOptions(
            name='diningspace',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Zal yoki xona', 'verbose_name_plural': 'Zallar va xonalar'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('-date', '-time', '-created_at'), 'verbose_name': 'Bron arizasi', 'verbose_name_plural': 'Bron arizalari'},
        ),
        migrations.AlterModelOptions(
            name='reservationaction',
            options={'ordering': ('-created_at',), 'verbose_name': 'Amallar tarixi', 'verbose_name_plural': 'Amallar tarixi'},
        ),
        migrations.AlterModelOptions(
            name='reservationoccasion',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Tashrif sababi', 'verbose_name_plural': 'Tashrif sabablari'},
        ),
        migrations.AlterModelOptions(
            name='restaurantclosure',
            options={'ordering': ('date', 'from_time'), 'verbose_name': 'Restoran yopiq sana', 'verbose_name_plural': 'Restoran yopiq sanalari'},
        ),
        migrations.AlterModelOptions(
            name='sitevisitdaily',
            options={'ordering': ('-date',), 'verbose_name': 'Kunlik sayt statistikasi', 'verbose_name_plural': 'Kunlik sayt statistikasi'},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ('user__first_name', 'user__username'), 'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ('day_of_week',), 'verbose_name': 'Ish vaqti', 'verbose_name_plural': 'Ish vaqtlari'},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Nima sodir bo‘ldi'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='handled_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_complaints', to='reservations.staffprofile', verbose_name='Mas’ul xodim'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='place_details',
            field=models.CharField(blank=True, max_length=160, verbose_name='Xona, kabinka yoki stol raqami'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='public_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Shikoyat raqami'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reason',
            field=models.CharField(choices=[('CLEANLINESS', 'Xona yoki zal toza emas'), ('AIR', 'Havo dim yoki yoqimsiz'), ('COLD_FOOD', 'Taom issiq emas edi'), ('TASTE', 'Taomning ta’mi yoqmadi'), ('MISSING_ITEM', 'Buyurtmada nimadir yetishmadi'), ('SERVICE', 'Xizmat ko‘rsatish yoqmadi'), ('SLOW_SERVICE', 'Ofitsiant uzoq vaqt kelmadi'), ('OTHER', 'Boshqa sabab')], max_length=30, verbose_name='Shikoyat sababi'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yopilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ko‘rib chiqilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='reservations.diningspace', verbose_name='Zal yoki xona'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='staff_comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Xodim izohi'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('IN_REVIEW', 'Ko‘rib chiqilmoqda'), ('RESOLVED', 'Hal qilindi'), ('DISMISSED', 'Yopildi')], db_index=True, default='NEW', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='submission_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Yuborish kaliti'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='diningspace',
            name='capacity_max',
            field=models.PositiveSmallIntegerField(verbose_name='Eng ko‘p mehmonlar'),
        ),
        migrations.AlterField(
            model_name='diningspace',
            name='capacity_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Eng kam mehmonlar'),
        ),
        migrations.AlterField(
            model_name='diningspace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='diningspace',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsifi (ruscha)'),
        ),
        migrations.AlterField(
            model_name='diningspace',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Tavsifi (o‘zbekcha)'),
        ),
        migrations.AlterField(
            model_name='diningspace',
            name='hide_when_unavailable',
            field=models.BooleanField(default=False, verbose_name='Yopilganda yashirilsin'),
        ),
        migrations.AlterField(
            model_name='diningspace',
            name='image',
            field=models.ImageField(blank=True, upload_to='spaces/%Y/%m/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='diningspace',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Saytda ko‘rsatilsin'),
        ),
        migrations.AlterField(
            model_name='diningspace',
            name='is_bookable',
            field=models.BooleanField(default=True, verbose_name='Bron qilish mumkin'),
        ),
        migrations.AlterField(
            model_name='diningspace',
            name='is_exclusive',
            field=models.BooleanField(default=False, help_text='Bu joyda bir vaqtda faqat bitta tasdiqlangan bron bo‘lishi mumkin.', verbose_name='Faqat bitta davra uchun'),
        ),
        migrations.AlterField(
            model_name='diningspace',
            name='is_temporarily_unavailable',
            field=models.BooleanField(default=False, verbose_name='Vaqtincha yopilgan'),
        ),
        migrations.AlterField(
            model_name='diningspace',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Nomi (ruscha)'),
        ),
        migrations.AlterField(
            model_name='diningspace',
            name='name_uz',
            field=models.CharField(blank=True, max_length=160, verbose_name='Nomi (o‘zbekcha)'),
        ),
        migrations.AlterField(
            model_name='diningspace',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ko‘rsatish tartibi'),
        ),
        migrations.AlterField(
            model_name='diningspace',
            name='space_type',
            field=models.CharField(choices=[('HALL', 'Zal'), ('PRIVATE_ROOM', 'Alohida xona'), ('TERRACE', 'Ayvon'), ('VIP', 'VIP joy'), ('OTHER', 'Boshqa')], default='HALL', max_length=20, verbose_name='Joy turi'),
        ),
        migrations.AlterField(
            model_name='diningspace',
            name='unavailable_reason',
            field=models.CharField(blank=True, max_length=240, verbose_name='Yopilish sababi (ruscha)'),
        ),
        migrations.AlterField(
            model_name='diningspace',
            name='unavailable_reason_uz',
            field=models.CharField(blank=True, max_length=240, verbose_name='Yopilish sababi (o‘zbekcha)'),
        ),
        migrations.AlterField(
            model_name='diningspace',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan vaqt'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ariza yuborilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Mehmon izohi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(max_length=120, verbose_name='Mehmon ismi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(verbose_name='Tashrif sanasi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guests_count',
            field=models.PositiveSmallIntegerField(verbose_name='Mehmonlar soni'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='handled_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reservations', to='reservations.staffprofile', verbose_name='Mas’ul xodim'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='manager_comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Administrator izohi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='occasion',
            field=models.CharField(blank=True, max_length=30, verbose_name='Tashrif sababi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='proposed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Taklif qilingan sana'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='proposed_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Taklif qilingan vaqt'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='public_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Bron raqami'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Ochiq kuzatuv kaliti'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rad etilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='Rad etish sababi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.diningspace', verbose_name='Tanlangan joy'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Tasdiqlanishi kutilmoqda'), ('ACCEPTED', 'Tasdiqlandi'), ('CHANGE_PROPOSED', 'Boshqa vaqt taklif qilindi'), ('REJECTED', 'Rad etildi'), ('CANCELLED', 'Bekor qilindi'), ('COMPLETED', 'Yakunlandi'), ('NO_SHOW', 'Mehmon kelmadi')], db_index=True, default='PENDING', max_length=24, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='submission_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Yuborish kaliti'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(verbose_name='Tashrif vaqti'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='reservationaction',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Yaratildi'), ('ACCEPTED', 'Tasdiqlandi'), ('TIME_PROPOSED', 'Boshqa vaqt taklif qilindi'), ('PROPOSAL_ACCEPTED', 'Mehmon taklifni qabul qildi'), ('PROPOSAL_DECLINED', 'Mehmon taklifni rad etdi'), ('REJECTED', 'Rad etildi'), ('CANCELLED', 'Bekor qilindi'), ('COMPLETED', 'Yakunlandi'), ('SPACE_DISABLED', 'Joy vaqtincha yopildi'), ('SPACE_ENABLED', 'Joy ochildi')], max_length=30, verbose_name='Amal'),
        ),
        migrations.AlterField(
            model_name='reservationaction',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='reservations.staffprofile', verbose_name='Xodim'),
        ),
        migrations.AlterField(
            model_name='reservationaction',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='reservationaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Amal vaqti'),
        ),
        migrations.AlterField(
            model_name='reservationaction',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='reservations.reservation', verbose_name='Bron arizasi'),
        ),
        migrations.AlterField(
            model_name='reservationaction',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='reservations.diningspace', verbose_name='Joy'),
        ),
        migrations.AlterField(
            model_name='reservationoccasion',
            name='code',
            field=models.SlugField(help_text='Lotin harflari, raqam, chiziqcha yoki pastki chiziq. Masalan: anniversary', max_length=30, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='reservationoccasion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Bron formasida ko‘rsatilsin'),
        ),
        migrations.AlterField(
            model_name='reservationoccasion',
            name='name_ru',
            field=models.CharField(max_length=120, verbose_name='Nomi (ruscha)'),
        ),
        migrations.AlterField(
            model_name='reservationoccasion',
            name='name_uz',
            field=models.CharField(max_length=120, verbose_name='Nomi (o‘zbekcha)'),
        ),
        migrations.AlterField(
            model_name='reservationoccasion',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ko‘rsatish tartibi'),
        ),
        migrations.AlterField(
            model_name='restaurantclosure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='restaurantclosure',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='restaurantclosure',
            name='from_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='restaurantclosure',
            name='full_day',
            field=models.BooleanField(default=True, verbose_name='Kun bo‘yi'),
        ),
        migrations.AlterField(
            model_name='restaurantclosure',
            name='reason',
            field=models.CharField(max_length=240, verbose_name='Sabab'),
        ),
        migrations.AlterField(
            model_name='restaurantclosure',
            name='to_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='sitevisitdaily',
            name='date',
            field=models.DateField(unique=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='sitevisitdaily',
            name='unique_visitors',
            field=models.PositiveIntegerField(default=0, verbose_name='Noyob tashrifchilar'),
        ),
        migrations.AlterField(
            model_name='sitevisitdaily',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='sitevisitdaily',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Ko‘rishlar'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kirishga ruxsat berilgan'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Restoran egasi'), ('MANAGER', 'Administrator'), ('CONTENT_MANAGER', 'Kontent boshqaruvchisi')], default='MANAGER', max_length=20, verbose_name='Vazifasi'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='telegram_notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Telegram bildirishnomalari'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='close_time',
            field=models.TimeField(default='23:00', verbose_name='Yopilish vaqti'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], unique=True, verbose_name='Hafta kuni'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Dam olish kuni'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='open_time',
            field=models.TimeField(default='11:00', verbose_name='Ochilish vaqti'),
        ),
    ]
