# Generated by Django 5.2.6 on 2026-09-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=120, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(max_length=120, verbose_name='Название (RU)')),
                ('icon', models.CharField(blank=True, max_length=16, verbose_name='Belgi / иконка')),
                ('slug', models.SlugField(unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib / порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol / активно')),
            ],
            options={
                'verbose_name': 'Kategoriya / категория',
                'verbose_name_plural': 'Kategoriyalar / категории',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='Beshbarmak House', max_length=160, verbose_name='Restoran nomi / название')),
                ('subtitle_uz', models.CharField(default='Milliy taomlar • Issiq • Mazali', max_length=180, verbose_name='Taglavha (UZ)')),
                ('subtitle_ru', models.CharField(default='Национальная кухня • С пылу с жару', max_length=180, verbose_name='Подзаголовок (RU)')),
                ('about_uz', models.TextField(blank=True, verbose_name='Qisqa matn (UZ)')),
                ('about_ru', models.TextField(blank=True, verbose_name='Короткий текст (RU)')),
                ('phone', models.CharField(default='+998 90 123 45 67', max_length=40, verbose_name='Telefon')),
                ('working_hours_uz', models.CharField(default='Har kuni, 10:00–23:00', max_length=120, verbose_name='Ish vaqti (UZ)')),
                ('working_hours_ru', models.CharField(default='Ежедневно, 10:00–23:00', max_length=120, verbose_name='Время работы (RU)')),
                ('location_text_uz', models.CharField(default='Yangiyo‘l', max_length=180, verbose_name='Manzil (UZ)')),
                ('location_text_ru', models.CharField(default='Янгиюль', max_length=180, verbose_name='Адрес (RU)')),
                ('location_url', models.URLField(blank=True, verbose_name='Xarita havolasi / ссылка на карту')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('hero_image', models.ImageField(blank=True, upload_to='restaurant/', verbose_name='Asosiy rasm / фото обложки')),
                ('logo', models.ImageField(blank=True, upload_to='restaurant/', verbose_name='Logotip / логотип')),
            ],
            options={
                'verbose_name': 'Restoran sozlamalari / настройки ресторана',
                'verbose_name_plural': 'Restoran sozlamalari / настройки ресторана',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=160, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(max_length=160, verbose_name='Название (RU)')),
                ('description_uz', models.TextField(verbose_name='Tavsif (UZ)')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('price', models.PositiveIntegerField(verbose_name='Narx, so‘m / цена, сум')),
                ('weight', models.CharField(blank=True, max_length=60, verbose_name='Vazn yoki porsiya / вес или порция')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjud / в наличии')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Ko‘p tanlanadi / популярное')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Tavsiya / рекомендуем')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib / порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='menu.category', verbose_name='Kategoriya / категория')),
            ],
            options={
                'verbose_name': 'Taom / блюдо',
                'verbose_name_plural': 'Taomlar / блюда',
                'ordering': ('category__sort_order', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dishes/%Y/%m/', verbose_name='Rasm / фото')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib / порядок')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.dish', verbose_name='Taom / блюдо')),
            ],
            options={
                'verbose_name': 'Taom rasmi / фото блюда',
                'verbose_name_plural': 'Taom rasmlari / фото блюд',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
