# Generated by Django 5.2.6 on 2026-09-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_restaurantsettings_reservations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=180, verbose_name='Sarlavha (UZ)')),
                ('title_ru', models.CharField(max_length=180, verbose_name='Заголовок (RU)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (UZ)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('badge_uz', models.CharField(blank=True, default='Aksiya', max_length=80, verbose_name='Belgi (UZ)')),
                ('badge_ru', models.CharField(blank=True, default='Акция', max_length=80, verbose_name='Метка (RU)')),
                ('image', models.ImageField(blank=True, upload_to='promotions/%Y/%m/', verbose_name='Rasm / изображение')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='Havola / ссылка')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanishi / начало')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugashi / окончание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol / активно')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib / порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aksiya / акция',
                'verbose_name_plural': 'Aksiyalar / акции',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
    ]
