# Generated by Django 5.2.6 on 2026-09-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsettings',
            name='location_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Xarita havolasi / ссылка на карту'),
        ),
    ]
