# Generated by Django 5.2.6 on 2026-09-26 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_restaurantsettings_location_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Taom kategoriyasi', 'verbose_name_plural': 'Taom kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('category__sort_order', 'sort_order', 'id'), 'verbose_name': 'Taom', 'verbose_name_plural': 'Taomlar'},
        ),
        migrations.AlterModelOptions(
            name='dishimage',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Taom rasmi', 'verbose_name_plural': 'Taom rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ('sort_order', '-created_at'), 'verbose_name': 'Aksiya', 'verbose_name_plural': 'Aksiyalar'},
        ),
        migrations.AlterModelOptions(
            name='restaurantsettings',
            options={'verbose_name': 'Restoran sozlamalari', 'verbose_name_plural': 'Restoran sozlamalari'},
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='youtube_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/', verbose_name='YouTube havolasi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=16, verbose_name='Belgi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Saytda ko‘rsatilsin'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=120, verbose_name='Nomi (ruscha)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=120, verbose_name='Nomi (o‘zbekcha)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Manzil kodi (slug)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ko‘rsatish tartibi'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='menu.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description_ru',
            field=models.TextField(verbose_name='Tavsifi (ruscha)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description_uz',
            field=models.TextField(verbose_name='Tavsifi (o‘zbekcha)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Hozir mavjud'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Ko‘p tanlanadi'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Tavsiya qilinadi'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name_ru',
            field=models.CharField(max_length=160, verbose_name='Nomi (ruscha)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name_uz',
            field=models.CharField(max_length=160, verbose_name='Nomi (o‘zbekcha)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Narxi, so‘m'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ko‘rsatish tartibi'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='weight',
            field=models.CharField(blank=True, max_length=60, verbose_name='Vazni yoki porsiyasi'),
        ),
        migrations.AlterField(
            model_name='dishimage',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.dish', verbose_name='Taom'),
        ),
        migrations.AlterField(
            model_name='dishimage',
            name='image',
            field=models.ImageField(upload_to='dishes/%Y/%m/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='dishimage',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Rasm tartibi'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='badge_ru',
            field=models.CharField(blank=True, default='Акция', max_length=80, verbose_name='Belgisi (ruscha)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='badge_uz',
            field=models.CharField(blank=True, default='Aksiya', max_length=80, verbose_name='Belgisi (o‘zbekcha)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Tavsifi (ruscha)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Tavsifi (o‘zbekcha)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, upload_to='promotions/%Y/%m/', verbose_name='Banner rasmi'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Saytda ko‘rsatilsin'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='link_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Batafsil havolasi'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ko‘rsatish tartibi'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title_ru',
            field=models.CharField(max_length=180, verbose_name='Sarlavhasi (ruscha)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title_uz',
            field=models.CharField(max_length=180, verbose_name='Sarlavhasi (o‘zbekcha)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='about_ru',
            field=models.TextField(blank=True, verbose_name='Restoran haqida (ruscha)'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='about_uz',
            field=models.TextField(blank=True, verbose_name='Restoran haqida (o‘zbekcha)'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='cancellation_limit_hours',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Bekor qilish chegarasi, soat'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='default_reservation_duration_minutes',
            field=models.PositiveIntegerField(default=120, verbose_name='Bron davomiyligi, daqiqa'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='restaurant/', verbose_name='Sayt muqovasi'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram havolasi'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='location_text_ru',
            field=models.CharField(default='Янгиюль', max_length=180, verbose_name='Manzil (ruscha)'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='location_text_uz',
            field=models.CharField(default='Yangiyo‘l', max_length=180, verbose_name='Manzil (o‘zbekcha)'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='location_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Xarita havolasi'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='restaurant/', verbose_name='Logotip'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='manager_confirmation_required',
            field=models.BooleanField(default=True, verbose_name='Administrator tasdig‘i kerak'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='maximum_days_ahead',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Oldindan bron qilish muddati, kun'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='maximum_guests',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Eng ko‘p mehmonlar soni'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='minimum_advance_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Tashrifgacha eng kam vaqt, daqiqa'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='minimum_guests',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Eng kam mehmonlar soni'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='reservation_enabled',
            field=models.BooleanField(default=True, verbose_name='Bron qilish yoqilgan'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='restaurant_name',
            field=models.CharField(default='Beshbarmak House', max_length=160, verbose_name='Restoran nomi'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='slot_interval_minutes',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Vaqt oralig‘i, daqiqa'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='subtitle_ru',
            field=models.CharField(default='Национальная кухня • С пылу с жару', max_length=180, verbose_name='Taglavha (ruscha)'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='subtitle_uz',
            field=models.CharField(default='Milliy taomlar • Issiq • Mazali', max_length=180, verbose_name='Taglavha (o‘zbekcha)'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Telegram havolasi'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='working_hours_ru',
            field=models.CharField(default='Ежедневно, 10:00–23:00', max_length=120, verbose_name='Ish vaqti (ruscha)'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='working_hours_uz',
            field=models.CharField(default='Har kuni, 10:00–23:00', max_length=120, verbose_name='Ish vaqti (o‘zbekcha)'),
        ),
    ]
