# Generated by Django 5.2.6 on 2026-09-26 16:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_category_options_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Takrorlanmas yuborish kaliti')),
                ('guest_name', models.CharField(blank=True, max_length=80, verbose_name='Mehmon ismi')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Baho')),
                ('text', models.TextField(max_length=1000, verbose_name='Fikr')),
                ('language', models.CharField(choices=[('uz', 'O‘zbekcha'), ('ru', 'Ruscha')], default='uz', max_length=2, verbose_name='Fikr tili')),
                ('is_published', models.BooleanField(default=False, verbose_name='Saytda ko‘rsatilsin')),
                ('admin_note', models.CharField(blank=True, max_length=300, verbose_name='Administrator izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': 'Mehmon fikri',
                'verbose_name_plural': 'Mehmon fikrlari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DishLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='Tashrifchi kaliti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Bosilgan vaqt')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='menu.dish', verbose_name='Taom')),
            ],
            options={
                'verbose_name': 'Taomga yoqtirish',
                'verbose_name_plural': 'Taom yoqtirishlari',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('dish', 'session_key'), name='one_like_per_dish_and_session')],
            },
        ),
    ]
