# Generated by Django 5.2.6 on 2026-09-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_review_dishlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Tavsifi (ruscha)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Tavsifi (o‘zbekcha)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Narxi, so‘m'),
        ),
    ]
