# Generated by Django 5.2.6 on 2026-09-26 16:51

from django.db import migrations


CATALOG = (
    ("beshbarmoq", "Beshbarmoq", "Бешбармак", "𓎩", (
        ("Beshbarmoq", "Бешбармак", None),
    )),
    ("norin", "Norin", "Нарын", "🍜", (
        ("Norin — porsiya", "Нарын — порция", 50000),
        ("Norin — 1 kg + 3 dona qazi", "Нарын — 1 кг + 3 казы", 155000),
    )),
    ("shashliklar", "Shashliklar", "Шашлыки", "♨", (
        ("Qiyma shashlik", "Шашлык из фарша", None),
        ("Ot jaz shashlik", "Шашлык «От жаз»", None),
    )),
    ("baliq", "Baliq", "Рыба", "🐟", (
        ("Baliq (dona)", "Рыба (штука)", None),
        ("Baliq — 1 kg dan yuqori", "Рыба — свыше 1 кг", None),
        ("Baliq — 2 kg dan yuqori", "Рыба — свыше 2 кг", None),
    )),
    ("salatlar", "Salatlar", "Салаты", "🥗", (
        ("Svejiy", "Свежий", None),
        ("Achiq-chuchuk", "Ачичук", None),
        ("Morskoy kapriz", "Морской каприз", None),
        ("Yaponskiy", "Японский", None),
        ("Chiroqchi", "Чирокчи", None),
        ("Suzma", "Сузьма", None),
        ("Smak", "Смак", None),
        ("Sezar", "Цезарь", None),
    )),
    ("ichimliklar", "Ichimliklar", "Напитки", "🥤", (
        ("Choy", "Чай", None),
        ("Limonli choy", "Чай с лимоном", None),
        ("Coca-Cola 1 L", "Coca-Cola 1 л", None),
        ("Coca-Cola 1,5 L", "Coca-Cola 1,5 л", None),
        ("Pepsi 1 L", "Pepsi 1 л", None),
        ("Pepsi 1,5 L", "Pepsi 1,5 л", None),
        ("Fanta 1 L", "Fanta 1 л", None),
        ("Fanta 1,5 L", "Fanta 1,5 л", None),
        ("Gazsiz suv 1 L", "Вода без газа 1 л", None),
        ("Gazli suv 1 L", "Газированная вода 1 л", None),
        ("Chortoq", "Чартак", None),
        ("Moxito", "Мохито", None),
        ("Moxito 1 L", "Мохито 1 л", None),
        ("Kokteyl", "Коктейль", None),
    )),
)


def replace_catalog(apps, schema_editor):
    Category = apps.get_model("menu", "Category")
    Dish = apps.get_model("menu", "Dish")
    Promotion = apps.get_model("menu", "Promotion")

    Dish.objects.all().delete()
    Category.objects.all().delete()
    dish_order = 0
    for category_order, (slug, name_uz, name_ru, icon, dishes) in enumerate(CATALOG, start=1):
        category = Category.objects.create(
            slug=slug,
            name_uz=name_uz,
            name_ru=name_ru,
            icon=icon,
            sort_order=category_order * 10,
            is_active=True,
        )
        for dish_name_uz, dish_name_ru, price in dishes:
            dish_order += 1
            Dish.objects.create(
                category=category,
                name_uz=dish_name_uz,
                name_ru=dish_name_ru,
                description_uz="",
                description_ru="",
                price=price,
                weight="",
                is_available=True,
                is_popular=False,
                is_recommended=False,
                sort_order=dish_order,
            )

    # Previous demo offers contained prices that no longer match the menu.
    Promotion.objects.update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_dish_description_ru_alter_dish_description_uz_and_more'),
    ]

    operations = [
        migrations.RunPython(replace_catalog, migrations.RunPython.noop),
    ]
